-- Sunwealth seed data. Local development only.
-- Every record is titled with [PLACEHOLDER] — never ship to production.

-- =====================================================================
-- Agent
-- =====================================================================
INSERT INTO agents (id, name, role, sub_brand, email, whatsapp, cal_booking_url, is_active)
VALUES (
  '00000000-0000-0000-0000-000000000a01',
  '[PLACEHOLDER] Adaeze Okafor',
  'senior',
  'all',
  'placeholder-agent@sunwealthrealestate.com',
  '+2349038379755',
  'https://cal.com/sunwealth/placeholder',
  TRUE
);

-- =====================================================================
-- Properties — one per sub-brand
-- =====================================================================

-- Sale — Banana Island duplex
INSERT INTO properties (
  id, slug, title, category, listing_type, status, sub_brand,
  location, price, size, bedrooms, bathrooms,
  features, documents, images, description,
  nearby_landmarks, payment_plans, virtual_tour_url,
  published_at
)
VALUES (
  '00000000-0000-0000-0000-000000000b01',
  'placeholder-ikoyi-duplex',
  '[PLACEHOLDER] 5-bedroom fully detached duplex, Banana Island',
  'fully-detached-duplex',
  'sale',
  'available',
  'sales',
  '{"area":"Banana Island","city":"Lagos","state":"Lagos State"}'::jsonb,
  '{"amount":850000000,"currency":"NGN","basis":"outright"}'::jsonb,
  '{"value":850,"unit":"sqm"}'::jsonb,
  5, 6,
  ARRAY['Swimming pool','BQ','24/7 power','Fully fitted kitchen','Smart home system'],
  ARRAY['C of O'],
  '[{"src":"https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1600","alt":"[PLACEHOLDER] Front elevation of 5-bedroom duplex","isPrimary":true,"order":0}]'::jsonb,
  'Placeholder description — replace with real property copy before launch.',
  ARRAY['Banana Island Club','Federal Palace Hotel'],
  '[]'::jsonb,
  NULL,
  now() - interval '2 days'
);

-- Rental — Lekki Phase 1 apartment
INSERT INTO properties (
  id, slug, title, category, listing_type, status, sub_brand,
  location, price, size, bedrooms, bathrooms,
  features, documents, images, description,
  nearby_landmarks, payment_plans, virtual_tour_url,
  published_at
)
VALUES (
  '00000000-0000-0000-0000-000000000b02',
  'placeholder-lekki-apartment',
  '[PLACEHOLDER] 3-bedroom apartment, Lekki Phase 1',
  'apartment',
  'rent',
  'available',
  'rent',
  '{"area":"Lekki Phase 1","city":"Lagos","state":"Lagos State"}'::jsonb,
  '{"amount":18000000,"currency":"NGN","basis":"per-annum"}'::jsonb,
  '{"value":180,"unit":"sqm"}'::jsonb,
  3, 3,
  ARRAY['Gym','Swimming pool','24/7 security','Parking'],
  ARRAY['Governor''s Consent'],
  '[{"src":"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600","alt":"[PLACEHOLDER] Living area of 3-bedroom apartment","isPrimary":true,"order":0}]'::jsonb,
  'Placeholder description — replace with real property copy before launch.',
  ARRAY['Lekki Conservation Centre'],
  '[]'::jsonb,
  NULL,
  now() - interval '5 days'
);

-- Land — VGC plot
INSERT INTO properties (
  id, slug, title, category, listing_type, status, sub_brand,
  location, price, size, bedrooms, bathrooms,
  features, documents, images, description,
  nearby_landmarks, payment_plans, virtual_tour_url,
  published_at
)
VALUES (
  '00000000-0000-0000-0000-000000000b03',
  'placeholder-vgc-plot',
  '[PLACEHOLDER] 1,000 sqm plot, Victoria Garden City',
  'land',
  'sale',
  'available',
  'land',
  '{"area":"Victoria Garden City","city":"Lagos","state":"Lagos State"}'::jsonb,
  '{"amount":150000000,"currency":"NGN","basis":"per-plot"}'::jsonb,
  '{"value":1000,"unit":"sqm"}'::jsonb,
  NULL, NULL,
  ARRAY['Dry land','Tarred access road'],
  ARRAY['Registered Survey','Deed of Assignment'],
  '[{"src":"https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600","alt":"[PLACEHOLDER] Aerial view of vacant plot at VGC","isPrimary":true,"order":0}]'::jsonb,
  'Placeholder description — replace with real property copy before launch.',
  ARRAY['VGC Gate','Nicon Town'],
  '[{"label":"12-month plan","duration":"12 months","note":"30% down, balance spread across 12 months"}]'::jsonb,
  NULL,
  now() - interval '10 days'
);

-- =====================================================================
-- Knowledge documents (embeddings left NULL — generated by a later step)
-- =====================================================================

INSERT INTO knowledge_documents (id, title, category, content) VALUES
(
  '00000000-0000-0000-0000-000000000c01',
  '[PLACEHOLDER] Property verification process',
  'verification',
  E'Every Sunwealth listing is verified before publishing. Our verification includes:\n- Title document review\n- Physical site inspection\n- Vendor identity check\n\nReplace this placeholder with the authoritative process.'
),
(
  '00000000-0000-0000-0000-000000000c02',
  '[PLACEHOLDER] Refund and cancellation policy',
  'payment',
  E'Inspection fees are refundable against a successful purchase completed within 90 days.\n\nReplace this placeholder with the real refund policy.'
),
(
  '00000000-0000-0000-0000-000000000c03',
  '[PLACEHOLDER] Diaspora buying guide',
  'diaspora',
  E'Buying from abroad with Sunwealth:\n1. Discover — shortlist via the website or concierge\n2. Virtual inspection with a senior agent\n3. Documents verified before wire\n4. Keys handed over remote or on the ground\n\nReplace this placeholder with the full diaspora playbook.'
);
